name: Test

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            node: 10.x
          - os: ubuntu-latest
            node: 12.x
          - os: ubuntu-latest
            node: 14.x
          - os: windows-latest
            node: 10.x
          - os: windows-latest
            node: 12.x
          - os: windows-latest
            node: 14.x
          - os: macos-latest
            node: 16.x
          - os: macos-latest
            node: 18.x

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Install modules
        run: yarn
      - name: Build
        run: yarn build
      - name: Run tests
        run: yarn test
